### ISSUE TITLE
collapsed/scrolled inconsistency

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter-js-output-area#25]
```
IOutputAreaViewModel {
  collapsed: boolean;
  scrolled: boolean;
  ...
}
```

Collapsed and scrolled are mutually exclusive, so 2 booleans seem like bad interface. 
I propose an enum:
- expanded
- scrolled
- collapsed

Will make logics much more easier to deal with, and we can add states. 
Also incurrent notebook, because of this double boolean, the are UI inconsistencies.

**Comment by Carreau** [comment]
ping @ellisonbg

**Comment by Carreau** [comment]
And ping @fperez that need to start writing JS/TS

**Comment by jasongrout** [comment]
The reason we had them separate was because when you collapse and uncollapse, you want to maintain the scroll state.  You can't do that easily with a tri-state switch.

**Comment by jasongrout** [comment]
by the way, I've been changing scrolled to fixedHeight, which is more descriptive and correct (even if it is still kind of ugly, and still not quite correct)

**Comment by fperez** [comment]
Got it, @jasongrout's argument seems to make sense to me. @Carreau, thoughts?

**Comment by ellisonbg** [comment]
That is how I remember it as well. Also, I think the fixedHeight rename
make sense.

On Tue, Dec 8, 2015 at 2:45 PM, Fernando Perez notifications@github.com
wrote:

> Got it, @jasongrout https://github.com/jasongrout's argument seems to
> make sense to me. @Carreau https://github.com/Carreau, thoughts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/jupyter-js-output-area/issues/25#issuecomment-163044912
> .

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
> The reason we had them separate was because when you collapse and uncollapse, you want to maintain the scroll state.

Make (some) theoretical sens, that's not how the notebook behave now. 
if you : 
- set scroll
- set collapse
- unset collapse
    -(cell is not scrolled)
- unset scroll
    -(cell is not scrolled)
- set scroll

I'm also not 100% sure that keeping the scroll state while collapsed is the right thing we want to do, I think that something like https://github.com/jupyter/notebook/issues/807 is more intuitive.

Keeping the collapse state is unintuitive, as when you have a collapse state, you have no clue in which state it will end. A Collapse <-> fixed height <-> expanded 3 states seem to be much more mentally sane, than a 2x2 state where 2 of the 4 states have the same visual appearance.

Note, I can also imagine 4 state:
- collapsed
- fixedHeight (overflow hidden, equivalent of "head" on a file)
- fixedHeight (overflow scroll)
- expanded

**Comment by rgbkrk** [comment]
Closing, since this repo is now deprecated.
