### ISSUE TITLE
Polyfill Symbol for Safari

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/jupyter-js-output-area#3]
When attempting to use jupyter-js-output-area on Safari, this error comes up:

```
ReferenceError: Can't find variable: Symbol
```

jupyter js output area is then not able to be loaded. This particularly affects the `set`ter.

[`Symbol`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) is available in Firefox, Chrome, and Opera, but not in Safari or IE. There are polyfills:
- es6-symbol - https://www.npmjs.com/package/es6-symbol (Just `Symbol`)
- Babel's own polyfill - https://babeljs.io/docs/usage/polyfill/
- core-js - the whole kit and kaboodle; noticed performance wasn't the best...

**Comment by rgbkrk** [comment]
Here's Babel's polyfill: https://cdnjs.com/libraries/babel-core

**Comment by captainsafia** [comment]
I'm unable to reproduce this. Is it still an issue?

**Comment by zloirock** [comment]
`babel-polyfill` === `core-js/shim` + `regenerator/runtime` :)

**Comment by rgbkrk** [comment]
Nope! The latest Safari has `Symbol`. This can be closed!

**Comment by bradparks** [comment]
Hey! I'm using a WKWebView in an app, and found I had to use the Polyfill to make it work
I just included the lib as detailed here:

https://babeljs.io/docs/usage/polyfill/

`import "babel-polyfill";`

and that fixed it for me!

**Comment by rgbkrk** [comment]
Oh cool, what app?

**Comment by bradparks** [comment]
Hey... it's a Alfred like UI in [Hammerspoon](http://www.hammerspoon.org/), but I haven't completed it yet... thanks!
