### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/jupyter-js-output-area#5]
We need to add tests, likely adopting `mocha` again.

**Comment by captainsafia** [comment]
I can take a look at this.

I love me some mocha. :coffee:

**Comment by rgbkrk** [comment]
Ditto.

![img_3807](https://cloud.githubusercontent.com/assets/836375/9609689/a259eb6e-509a-11e5-8708-06d031bb47d8.JPG)

For similar reference code, the [transformime](https://github.com/nteract/transformime) tests are all in mocha.
