### ISSUE TITLE
support kernels that do weird things

### ISSUE THREAD

**Issue by willwhitney** [jupyter/jupyter-js-output-area#7]
The iTorch kernel and the IJulia kernel both send their results as `msg_type: "pyout"`, for example.

Clearly we need to have a forcing function to make the kernels standardize and follow the spec, but for the moment I think here isn't the right place.

**Comment by rgbkrk** [comment]
`pyout` and `pyerr` are legacies of old message specs, if I recall correctly. Do we have the old message specs documented in a series @minrk?

**Comment by minrk** [comment]
Since this is new code, I wouldn't support the old message spec. I would assume that kernels speaking the old spec are adapted to the current version, which is what the notebook server does.

**Comment by minrk** [comment]
But the v4 spec [is documented](http://ipython.org/ipython-doc/2/development/messaging.html).

**Comment by rgbkrk** [comment]
Ah right, `IPython 2.0 -> msg spec v4`

**Comment by rgbkrk** [comment]
Closing, since this repo is now deprecated.
